name: efabless_tool
# either manually started, or on a schedule
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # At 4:00 UTC everyday
jobs:
  build_cache:

    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v2

    # need python
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7' # install the python version needed

    # python deps from reqirements file, use a marketplace action
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: "requirements.txt"

    # run the caravel test
    - name: update cache
      run: python ./efabless_tool.py --update-cache
